name: Ping Server

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the server
        run: |
          echo "핑 보내는 시각: $(date)"
          curl -s https://fourword-task0.onrender.com/ || echo "핑 실패!"
